# Prometheus Configuration for AI Chatbot System
# Enterprise-grade monitoring with custom exporters and service discovery

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ai-chatbot-prod'
    environment: 'production'
    region: 'us-east-1'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

# Rules files
rule_files:
  - "rules/*.yml"
  - "sli_slo_rules/*.yml"
  - "cost_monitoring_rules/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node Exporter - System metrics
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
      - role: node
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        target_label: __address__
        replacement: '${1}:9100'
      - source_labels: [__meta_kubernetes_node_name]
        target_label: instance
    scrape_interval: 30s

  # AI Chatbot API Services
  - job_name: 'chatbot-api'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - ai-chatbot
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: 'chatbot-api'
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: 'metrics'
        action: keep
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: service
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod
    scrape_interval: 15s
    metrics_path: /metrics

  # Authentication Service
  - job_name: 'auth-service'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - ai-chatbot
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: 'auth-service'
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: 'metrics'
        action: keep
    scrape_interval: 15s

  # WebSocket Service
  - job_name: 'websocket-service'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - ai-chatbot
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name]
        regex: 'websocket-service'
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        regex: 'metrics'
        action: keep
    scrape_interval: 15s

  # Redis - Cache and Session Store
  - job_name: 'redis'
    static_configs:
      - targets: 
          - 'redis-master:9121'
          - 'redis-replica-1:9121'
          - 'redis-replica-2:9121'
    scrape_interval: 30s

  # PostgreSQL Database
  - job_name: 'postgresql'
    static_configs:
      - targets: 
          - 'postgres-primary:9187'
          - 'postgres-replica-1:9187'
          - 'postgres-replica-2:9187'
    scrape_interval: 30s

  # Elasticsearch for Logging
  - job_name: 'elasticsearch'
    static_configs:
      - targets: 
          - 'elasticsearch-master-1:9114'
          - 'elasticsearch-master-2:9114'
          - 'elasticsearch-master-3:9114'
    scrape_interval: 30s

  # NGINX Ingress Controller
  - job_name: 'nginx-ingress'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
            - ingress-nginx
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
    scrape_interval: 30s

  # Istio Service Mesh
  - job_name: 'istio-mesh'
    kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
            - istio-system
    relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: istio-proxy;http-monitoring
    scrape_interval: 15s

  # AWS CloudWatch Exporter
  - job_name: 'cloudwatch-exporter'
    static_configs:
      - targets: ['cloudwatch-exporter:9106']
    scrape_interval: 60s
    scrape_timeout: 60s

  # Cost Monitoring Custom Exporter
  - job_name: 'cost-exporter'
    static_configs:
      - targets: ['cost-exporter:8080']
    scrape_interval: 300s # 5 minutes
    scrape_timeout: 60s

  # AI Model Performance Exporter
  - job_name: 'ai-model-exporter'
    static_configs:
      - targets: ['ai-model-exporter:8081']
    scrape_interval: 30s

  # Business Metrics Exporter
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['business-metrics-exporter:8082']
    scrape_interval: 60s

  # JVM Metrics (if using Java services)
  - job_name: 'jvm-micrometer'
    kubernetes_sd_configs:
      - role: pod
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
        action: replace
        target_label: __metrics_path__
        regex: (.+)
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        target_label: __address__
    scrape_interval: 15s

  # Blackbox Exporter for External Services
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
          - https://api.openai.com
          - https://api.anthropic.com
          - https://api.cohere.ai
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    scrape_interval: 60s

  # Custom Application Metrics
  - job_name: 'custom-metrics'
    kubernetes_sd_configs:
      - role: pod
        namespaces:
          names: ['ai-chatbot']
    relabel_configs:
      - source_labels: [__meta_kubernetes_pod_label_app]
        regex: '(chatbot-.*)'
        action: keep
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_port]
        action: replace
        regex: (\d+)
        target_label: __address__
        replacement: ${__meta_kubernetes_pod_ip}:$1
    scrape_interval: 15s

# Remote write for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.monitoring.svc.cluster.local:9201/write"
    write_relabel_configs:
      - source_labels: [__name__]
        regex: 'chatbot_.*'
        action: keep
    queue_config:
      max_samples_per_send: 10000
      capacity: 100000
      batch_send_deadline: 5s

# Remote read for querying historical data
remote_read:
  - url: "https://prometheus-remote-read.monitoring.svc.cluster.local:9201/read"
    read_recent: true